/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fspack;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amitv
 */
public class searchtransactions extends javax.swing.JFrame {
int count=0;
    /**
     * Creates new form searchtransactions
     */
    public searchtransactions() {
        initComponents();
        jLabel2.setVisible(false);
        //seachtransactionstable.setVisible(false);
        String buff;
        String accid=jTextField1.getText();
        try {
            Scanner reader=new Scanner(new File("C:\\Users\\amitv\\Documents\\NetBeansProjects\\fsminiproject\\journal.txt"));
            reader.useDelimiter("\n");
            while(reader.hasNext())
            {
                buff=reader.next();
                count++;
            }
            reader.close();
            System.out.println("Count: "+count);
                    
        } catch (FileNotFoundException ex) {
            Logger.getLogger(searchtransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        seachtransactionstable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seachtransactionstable.setAutoCreateRowSorter(true);
        seachtransactionstable.setBackground(new java.awt.Color(51, 51, 51));
        seachtransactionstable.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        seachtransactionstable.setForeground(new java.awt.Color(255, 255, 255));
        seachtransactionstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Acc id", "Crypt Name", "Price", "Bs amount", "Type"
            }
        ));
        jScrollPane1.setViewportView(seachtransactionstable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 196, 870, 240));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 160, 32));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acc. No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 130, 35));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fspack/search2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 90, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 360, 60));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fspack/back1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 100, 100));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 240, 70));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 10)); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 90, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 10)); // NOI18N
        jButton4.setText("GO BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fspack/search.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String str,name=null,accno=null,cryptname=null,bsamt=null,price=null,type=null;
        DefaultTableModel model=(DefaultTableModel) seachtransactionstable.getModel();
        int flag = 0;
        int f=0;
        String accid=jTextField1.getText();
        try {
            Scanner reader=new Scanner(new File("C:\\Users\\amitv\\Documents\\NetBeansProjects\\fsminiproject\\journal.txt"));
            reader.useDelimiter("\r\n");
            for(int i=0;i<count;i++)
            {
                flag=0;
                str=reader.next();
                Scanner scan=new Scanner(str).useDelimiter(",");
                name=scan.next();
                accno=scan.next();
                cryptname=scan.next();
                price=scan.next();
                bsamt=scan.next();
                type=scan.next();
                if(accid.equals(accno))
                {
                   flag=1; 
                   f=1;
                   jLabel2.setVisible(true);
                   jLabel2.setText("Search Succesful");
                   //seachtransactionstable.setVisible(true);
                  // System.out.println("Search Succesful");
                   model.addRow(new Object[]{name,accno,cryptname,price,bsamt,type});
                   //break;
                }
                
            }
            reader.close();
            if(f==0)
            {
               // System.out.println("Search Unsuccesful");
                jLabel2.setVisible(true);
                jLabel2.setText("Search Unsuccesful");
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(searchtransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
        new homepagenew().setVisible(true);  

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String str,name=null,accno=null,cryptname=null,bsamt=null,price=null,type=null;
        DefaultTableModel model=(DefaultTableModel) seachtransactionstable.getModel();
        int flag = 0;
        int f=0;
        String accid=jTextField1.getText();
        try {
            Scanner reader=new Scanner(new File("C:\\Users\\amitv\\Documents\\NetBeansProjects\\fsminiproject\\journal.txt"));
            reader.useDelimiter("\r\n");
            for(int i=0;i<count;i++)
            {
                flag=0;
                str=reader.next();
                Scanner scan=new Scanner(str).useDelimiter(",");
                name=scan.next();
                accno=scan.next();
                cryptname=scan.next();
                price=scan.next();
                bsamt=scan.next();
                type=scan.next();
                if(accid.equals(accno))
                {
                   flag=1; 
                   f=1;
                   jLabel2.setVisible(true);
                   jLabel2.setText("Search Succesful");
                   //seachtransactionstable.setVisible(true);
                  // System.out.println("Search Succesful");
                   model.addRow(new Object[]{name,accno,cryptname,price,bsamt,type});
                   //break;
                }
                
            }
            reader.close();
            if(f==0)
            {
               // System.out.println("Search Unsuccesful");
                jLabel2.setVisible(true);
                jLabel2.setText("Search Unsuccesful");
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(searchtransactions.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.setVisible(false);
        new homepagenew().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchtransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable seachtransactionstable;
    // End of variables declaration//GEN-END:variables
}
